### ISSUE TITLE
🐛 Can not start Process via Start-Button in the Details View

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#145]
#### Describe your issue

When i try to start a Process via the Start-Button in the Details View, i always get the following error message:
```
container.ts:481 Unhandled rejection TypeError: Cannot read property 'hasAttribute' of undefined
    at ProcessDefDetail.<anonymous> (http://localhost:9000/scripts/app-bundle.js:1702:50)
    at step (http://localhost:9000/scripts/vendor-bundle.js:184226:23)
    at Object.next (http://localhost:9000/scripts/vendor-bundle.js:184207:53)
    at http://localhost:9000/scripts/vendor-bundle.js:183347:71
    at Promise._execute (http://localhost:9000/scripts/vendor-bundle.js:824:9)
    at Promise._resolveFromExecutor (http://localhost:9000/scripts/vendor-bundle.js:2601:18)
    at new Promise (http://localhost:9000/scripts/vendor-bundle.js:2197:10)
    at __awaiter (http://localhost:9000/scripts/vendor-bundle.js:183343:12)
    at ProcessDefDetail.startProcess (http://localhost:9000/scripts/app-bundle.js:1697:20)
    at CallScope.evaluate (http://localhost:9000/scripts/vendor-bundle.js:8002:21)
    at Listener.callSource (http://localhost:9000/scripts/vendor-bundle.js:11624:42)
    at Listener.handleEvent (http://localhost:9000/scripts/vendor-bundle.js:11633:12)
    at HTMLDocument.handleDelegatedEvent (http://localhost:9000/scripts/vendor-bundle.js:9743:22)
```
If i start a Process via the Process Definition List it works as it should.

#### How can others reproduce the issue?

* run BPMN-Studio
* open the details view of any process
* press the start button

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
@Vyperus is currenlty looking at this

**Comment by SteffenKn** [comment]
@alexanderkasten told me he fixed it already
