### ISSUE TITLE
🐛 BPMN Studio 5.8 isn't compatible with older ProcessEngines

### ISSUE THREAD

**Issue by roblen45** [process-engine/bpmn-studio#1771]
## Description

In my case I update my BPMN Studio to version 5.8.
After that I'am not able to deploy my Process to the Portal ProcessEngine in version 8.4.1.
It fails with the following error:

```
2019-10-07T09:58:52.833Z - info: [http_extension:error_handler] 422 { UnprocessableEntityError: The XML for process "MassagePlanen" could not be parsed.
    at ProcessModelService.validateDefinition (/usr/local/lib/node_modules/@process-engine/process_engine_runtime/node_modules/@process-engine/process_model.service/dist/commonjs/process_model_service.js:76:34)
  _code: 422,
  name: 'UnprocessableEntityError',
  _additionalInformation:
   TypeError: Cannot create property 'enabled' on string ''
       at assignEventDefinition (/usr/local/lib/node_modules/@process-engine/process_engine_runtime/node_modules/@process-engine/process_engine_core/dist/commonjs/model/parser/flow_node_parsers/event_parser.js:154:47)
       at assignEventDefinitions (/usr/local/lib/node_modules/@process-engine/process_engine_runtime/node_modules/@process-engine/process_engine_core/dist/commonjs/model/parser/flow_node_parsers/event_parser.js:123:5)
       at parseEventsByType (/usr/local/lib/node_modules/@process-engine/process_engine_runtime/node_modules/@process-engine/process_engine_core/dist/commonjs/model/parser/flow_node_parsers/event_parser.js:97:9)
       at Object.parseEventsFromProcessData (/usr/local/lib/node_modules/@process-engine/process_engine_runtime/node_modules/@process-engine/process_engine_core/dist/commonjs/model/parser/flow_node_parsers/event_parser.js:13:25)
       at Object.parseProcessFlowNodes (/usr/local/lib/node_modules/@process-engine/process_engine_runtime/node_modules/@process-engine/process_engine_core/dist/commonjs/model/parser/flow_node_parser.js:6:56)
       at Object.parseProcesses (/usr/local/lib/node_modules/@process-engine/process_engine_runtime/node_modules/@process-engine/process_engine_core/dist/commonjs/model/parser/process_parser.js:20:60)
       at convertToInternalObjectModel (/usr/local/lib/node_modules/@process-engine/process_engine_runtime/node_modules/@process-engine/process_engine_core/dist/commonjs/model/parser/definitions_parser.js:13:59)
       at Object.parseDefinitions (/usr/local/lib/node_modules/@process-engine/process_engine_runtime/node_modules/@process-engine/process_engine_core/dist/commonjs/model/parser/definitions_parser.js:7:12)
       at BpmnModelParser.parseXmlToObjectModel (/usr/local/lib/node_modules/@process-engine/process_engine_runtime/node_modules/@process-engine/process_engine_core/dist/commonjs/model/bpmn_model_parser.js:22:63) }

```

**Comment by alexanderkasten** [comment]
You must select the type of the Timer StartEvent.

**Comment by SteffenKn** [comment]
It seems that this issue occurs when trying to deploy a processModel with an unconfigured TimerStartEvent.
This does not happen when deploying it to the latest ProcessEngine but e.g. to v4.8.1.

**Comment by SteffenKn** [comment]
Im closing this since this is not an issue with the Studio, but an issue with the runtime: https://github.com/process-engine/process_engine_runtime/issues/437

Unconfigured TimerStartEvents should not be deployable.
