### ISSUE TITLE
ProcessEngine Database view is not updated/empty when uploading a process to a ProcessEngine

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#710]
#### Describe your issue
When uploading a new Process from a Solution to the ProcessEngine, the Solution explorer is empty/not updated. 

![aug-02-2018 15-25-00](https://user-images.githubusercontent.com/38498731/43586615-6292ea00-9668-11e8-91c9-837792e98353.gif)

Also, when I try to navigate to the Plan view, nothing really happens. 

This is the log - Output I get: 
```

browser-raw.js:93 Unhandled rejection InternalServerError: Cannot read property 'id' of undefined
    at HttpFetchClient.<anonymous> (file:///Volumes/bpmn-studio%204.0.0-pre-b254/bpmn-studio.app/Contents/Resources/app.asar/scripts/app-bundle.js:3629:39)
    at step (file:///Volumes/bpmn-studio%204.0.0-pre-b254/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28841:23)
    at Object.next (file:///Volumes/bpmn-studio%204.0.0-pre-b254/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28822:53)
    at fulfilled (file:///Volumes/bpmn-studio%204.0.0-pre-b254/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28813:58)
    at tryCatcher (file:///Volumes/bpmn-studio%204.0.0-pre-b254/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:3414:23)
    at Promise._settlePromiseFromHandler (file:///Volumes/bpmn-studio%204.0.0-pre-b254/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:2630:31)
    at Promise._settlePromise (file:///Volumes/bpmn-studio%204.0.0-pre-b254/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:2687:18)
    at Promise._settlePromise0 (file:///Volumes/bpmn-studio%204.0.0-pre-b254/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:2732:10)
    at Promise._settlePromises (file:///Volumes/bpmn-studio%204.0.0-pre-b254/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:2811:18)
    at Async._drainQueue (file:///Volumes/bpmn-studio%204.0.0-pre-b254/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:163:16)
    at Async._drainQueues (file:///Volumes/bpmn-studio%204.0.0-pre-b254/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:173:10)
    at Async.drainQueues (file:///Volumes/bpmn-studio%204.0.0-pre-b254/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:47:14)
    at <anonymous>
```

#### How can others reproduce the issue?
* Upload a process to the ProcessEngine
* Look at the database view of the Solution Explorer

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
It seems to be an issue with the old database. Deleting the old database fixed this issue for me.
