### ISSUE TITLE
🐛Escaping character in diagram title breaks the modeler

### ISSUE THREAD

**Issue by dominikkaminski** [process-engine/bpmn-studio#802]
#### Describe your issue

When using `>` or `"` as diagramname (filename) it brokes everything.

```json
browser-raw.js:93 Unhandled rejection Error: no definitions loaded
    at Modeler.Viewer.saveXML (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:57167:19)
    at file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/app-bundle.js:2084:39
    at Promise._execute (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:824:9)
    at Promise._resolveFromExecutor (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:2601:18)
    at new Promise (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:2197:10)
    at BpmnIo.<anonymous> (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/app-bundle.js:2083:37)
    at step (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28847:23)
    at Object.next (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28828:53)
    at file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28822:71
    at Promise._execute (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:824:9)
    at Promise._resolveFromExecutor (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:2601:18)
    at new Promise (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:2197:10)
    at __awaiter (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28818:12)
    at BpmnIo.getXML (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/app-bundle.js:2079:20)
    at BpmnIo.<anonymous> (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/app-bundle.js:2067:45)
    at step (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/vendor-bundle.js:28847:23)
```

#### How can others reproduce the issue?

Use `>` or `"` as diagram name.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
The behavior of both characters is kinda different: 

When using `"`, the studio look like this: 

<img width="1724" alt="screen shot 2018-08-16 at 14 14 22" src="https://user-images.githubusercontent.com/38498731/44207798-bb873c00-a15e-11e8-9820-ea75a5e84638.png">

And the full stack trace:
```

management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: illegal character after attribute end
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: illegal character after attribute end
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: illegal character after attribute end
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: illegal character after attribute end
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: illegal character after attribute end
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: illegal character after attribute end
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: illegal character after attribute end
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: illegal character after attribute end
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: illegal character after attribute end
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: illegal character after attribute end
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: illegal character after attribute end
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: illegal character after attribute end
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
```

With `>` the studio looks like this: 

<img width="1724" alt="screen shot 2018-08-16 at 14 15 57" src="https://user-images.githubusercontent.com/38498731/44207853-ebceda80-a15e-11e8-9852-801b67540182.png">

And the full resulting stack trace: 
```

management_api_client_service.ts:99 Error: missing closing quotes
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse document
handleError @ management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: closing tag mismatch
    at error (management_api_client_service.ts:99)
    at handleError (management_api_client_service.ts:99)
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: missing closing quotes
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse document
handleError @ management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: closing tag mismatch
    at error (management_api_client_service.ts:99)
    at handleError (management_api_client_service.ts:99)
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse node
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: missing closing quotes
    at error (management_api_client_service.ts:99)
    at handleWarning (management_api_client_service.ts:99)
    at Object.getAttrs [as attrs] (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
handleWarning @ management_api_client_service.ts:99
getAttrs @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 could not parse document
handleError @ management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
management_api_client_service.ts:99 Error: closing tag mismatch
    at error (management_api_client_service.ts:99)
    at handleError (management_api_client_service.ts:99)
    at parse (management_api_client_service.ts:99)
    at Parser.parse (management_api_client_service.ts:99)
    at management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
handleError @ management_api_client_service.ts:99
parse @ management_api_client_service.ts:99
Parser.parse @ management_api_client_service.ts:99
(anonymous) @ management_api_client_service.ts:99
property-panel.ts:76 Uncaught TypeError: Cannot read property 'rootElements' of undefined
    at property-panel.ts:76
    at management_api_client_service.ts:99
(anonymous) @ property-panel.ts:76
(anonymous) @ management_api_client_service.ts:99
container.ts:724 [31mUnhandled rejection Error: no definitions loaded
    at Modeler.Viewer.saveXML (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/vendor-bundle.js:57167:19)
    at file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/app-bundle.js:2148:39
    at Promise._execute (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/vendor-bundle.js:824:9)
    at Promise._resolveFromExecutor (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/vendor-bundle.js:2601:18)
    at new Promise (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/vendor-bundle.js:2197:10)
    at BpmnIo.<anonymous> (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/app-bundle.js:2147:37)
    at step (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/vendor-bundle.js:28847:23)
    at Object.next (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/vendor-bundle.js:28828:53)
    at file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/vendor-bundle.js:28822:71
    at Promise._execute (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/vendor-bundle.js:824:9)
    at Promise._resolveFromExecutor (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/vendor-bundle.js:2601:18)
    at new Promise (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/vendor-bundle.js:2197:10)
    at __awaiter (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/vendor-bundle.js:28818:12)
    at BpmnIo.getXML (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/app-bundle.js:2143:20)
    at BpmnIo.<anonymous> (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/app-bundle.js:1855:57)
    at step (file:///Users/robin/Documents/process_engine/process_engine_meta/bpmn-studio/scripts/vendor-bundle.js:28847:23)[0m

printWarning @ container.ts:724
formatAndLogError @ client.js:283
fireRejectionEvent @ client.js:308
Promise._notifyUnhandledRejection @ open-id-connect.ts:10
(anonymous) @ open-id-connect-factory.ts:22
```
